repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
        types_or: [python, cython]
      - id: check-builtin-literals
        types_or: [python, cython]
      # запрет размещения докстрингов перед кодом
      - id: check-docstring-first
        types_or: [python, cython]
      - id: check-case-conflict
        types_or: [python, cython]
      # запрет на коммит неразрешенных конфликтов мерджа гита
      - id: check-merge-conflict
        types_or: [python, cython]
      - id: end-of-file-fixer
        exclude_types: [xml]
        types_or: [python, cython]
      # запрет коммитов в мастер и в релиз
      - id: no-commit-to-branch
        types_or: [python, cython]
        args: [ --branch=master, --branch=release ]
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        additional_dependencies: [toml]
        types_or: [python, cython]
        args: [ -i, -vv, --style "google" ]
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        types_or: [python, cython]
  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa
        types_or: [python, cython]
  - repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        types_or: [python, cython]
        args: [
            --max-line-length=120
        ]
