name: Python application

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

#    - name: Build Postgres
#      working-directory: ./docker/
#      run: docker-compose -f application.docker-compose.yml up -d

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Run migrations
#      run: |
#        alembic upgrade head
#      env:
#        PG_USER: system_serv_one
#        PG_PASS: serv_one123
#        PG_DB: service_one
#      working-directory: ./src/service_one

    - name: Test with pytest
      working-directory: ./src/app
      run: |
        pytest